export const uiCopy = {
  fa: {
    home: 'خانه', learn: 'یادگیری', review: 'مرور', gym: 'باشگاه محصول',
    sidebarTitle: 'اول تمرین، بعد یادگیری', sidebarText: 'تصمیم‌های کوتاه با بازخورد فوری.',
    streak: 'روز پشت‌سرهم', heroEyebrow: 'تمرین تصمیم‌گیری محصول',
    heroTitle: 'مدیریت محصول را با تصمیم گرفتن یاد بگیر.',
    heroText: 'داستان کوتاه. انتخاب واقعی. بازخورد فوری.',
    startLearning: 'شروع یادگیری', continueLearning: 'ادامهٔ یادگیری',
    yourProgress: 'پیشرفت تو', lessonsCompleted: 'درس‌های تمام‌شده', discoverySkill: 'مهارت شناخت مشکل',
    demoControls: 'ابزارهای آزمایشی', resetDemo: 'پاک کردن پیشرفت', resetConfirm: 'همهٔ پاسخ‌ها و پیشرفت این دستگاه پاک شود؟',
    roadmapEyebrow: 'مسیر یادگیری', roadmapTitle: 'مسیر خودت را انتخاب کن',
    roadmapText: 'یک تصمیم بگیر و قدم بعدی را بردار.', completed: 'تمام‌شده',
    currentModule: 'بخش فعلی', discoveryModule: 'شناخت و بررسی فرصت‌ها',
    startLesson: 'شروع درس', continueLesson: 'ادامهٔ درس', viewRecap: 'دیدن نتیجه',
    exploreNext: 'موضوعات بعدی', upcomingAction: 'باز کردن', comingSoon: 'به‌زودی',
    comingSoonText: 'این درس هنوز آماده نیست.', backToRoadmap: 'بازگشت به مسیر',
    pillarReview: 'مرور آموخته‌ها', pillarGym: 'تمرین تصمیم', ready: 'آمادهٔ تمرین',
    reviewHomeTitle: 'یاد گرفته‌ها را دوباره به کار ببر.',
    gymHomeTitle: 'تو جای مدیر محصول تصمیم بگیر.',
    startPractice: 'شروع تمرین', continuePractice: 'ادامهٔ تمرین', viewResults: 'دیدن نتیجه',
    practiceComplete: 'تمرین تمام شد', questionsComplete: 'پرسش‌ها تمام شد',
    practiceRecapTitle: 'فکر کردی، تصمیم گرفتی، یاد گرفتی.',
    reviewRecap: 'همان فکر را در یک موقعیت تازه تمرین کردی.',
    gymRecap: 'با سرنخ‌های تازه و وقت محدود تصمیم گرفتی.',
    earnedPractice: 'امتیاز این تمرین', reviewQuestions: 'مرور پاسخ‌ها',
    previousQuestion: 'پرسش قبل', backToSection: 'بازگشت به',
    question: 'پرسش', step: 'گام', of: 'از',
    lessonComplete: 'درس تمام شد', lessonRecapText: 'چند تصمیم گرفتی و دیدی کدام سرنخ‌ها مهم‌ترند.',
    earnedLesson: 'امتیاز این درس', backHome: 'بازگشت به خانه', exploreLessons: 'دیدن درس‌ها',
    shareFeedback: 'نظرت را بگو', weeklyIntent: 'هر هفته این‌طور تمرین می‌کنی؟',
    definitely: 'بله', maybe: 'شاید', probablyNot: 'نه',
    feedbackQuestion: 'چه چیزی بهترش می‌کند؟ (دلخواه)', feedbackPlaceholder: 'یک پیشنهاد کوتاه…',
    saveResponse: 'ثبت نظر', savedHere: 'نظر فقط در همین دستگاه ذخیره می‌شود.',
    unavailable: 'درس پیدا نشد.', applyConcept: 'حالا امتحان کن',
    submitDecision: 'ثبت انتخاب', continue: 'ادامه', bestOrder: 'ترتیب بهتر',
    mostToLeast: 'از مفیدترین تا کم‌فایده‌ترین',
    moveUp: 'بالاتر بردن', moveDown: 'پایین‌تر بردن', submitRanking: 'بررسی ترتیب',
    chooseCategory: 'برای هر مورد یک دسته انتخاب کن', bestFit: 'دستهٔ بهتر',
    checkMap: 'بررسی پاسخ‌ها', placedWell: 'مورد درست دسته‌بندی شد',
    chooseExactly: 'انتخاب کن', useful: 'مفید', lessUseful: 'کم‌فایده',
    submitEvidence: 'ثبت سرنخ‌ها', multiCorrect: 'این دو سرنخ بیشتر به تصمیم کمک می‌کنند.',
    multiIncorrect: 'اول دنبال ارزشِ حل مشکل و تعداد افراد درگیر بگرد.',
    strongDecision: 'انتخاب خوب', partialDecision: 'تا حدی درست', notQuite: 'دقیق نیست',
    backToLessons: 'بازگشت به درس‌ها',
  },
  en: {
    home: 'Home', learn: 'Learn', review: 'Review', gym: 'PM Gym',
    sidebarTitle: 'Practice, then learn', sidebarText: 'Short decisions with quick feedback.',
    streak: 'day streak', heroEyebrow: 'PRODUCT DECISION PRACTICE',
    heroTitle: 'Learn Product Management by making decisions.',
    heroText: 'Short stories. Real choices. Quick feedback.',
    startLearning: 'Start learning', continueLearning: 'Continue learning',
    yourProgress: 'Your progress', lessonsCompleted: 'Lessons completed', discoverySkill: 'Discovery skill',
    demoControls: 'Demo controls', resetDemo: 'Reset progress', resetConfirm: 'Clear all answers and progress on this device?',
    roadmapEyebrow: 'LEARNING PATH', roadmapTitle: 'Choose your path',
    roadmapText: 'Make a decision, then take the next step.', completed: 'Completed',
    currentModule: 'CURRENT TOPIC', discoveryModule: 'Product Discovery & Validation',
    startLesson: 'Start lesson', continueLesson: 'Continue lesson', viewRecap: 'View recap',
    exploreNext: 'Explore what comes next', upcomingAction: 'Open', comingSoon: 'Coming soon',
    comingSoonText: 'This lesson is not ready yet.', backToRoadmap: 'Back to roadmap',
    pillarReview: 'REVISIT IDEAS', pillarGym: 'PRACTICE DECISIONS', ready: 'READY TO PRACTICE',
    reviewHomeTitle: 'Use what you learned again.',
    gymHomeTitle: 'Make the product call.',
    startPractice: 'Start practice', continuePractice: 'Continue practice', viewResults: 'View results',
    practiceComplete: 'Practice complete', questionsComplete: 'Questions complete',
    practiceRecapTitle: 'You thought, chose, and learned.',
    reviewRecap: 'You used the same ideas in a new situation.',
    gymRecap: 'You made a call with new clues and limited time.',
    earnedPractice: 'Earned in this practice', reviewQuestions: 'Review answers',
    previousQuestion: 'Previous question', backToSection: 'Back to',
    question: 'Question', step: 'Step', of: 'of',
    lessonComplete: 'Lesson complete', lessonRecapText: 'You made decisions and saw which clues matter most.',
    earnedLesson: 'Earned in this lesson', backHome: 'Back to Home', exploreLessons: 'Explore lessons',
    shareFeedback: 'Share feedback', weeklyIntent: 'Would you practice this way each week?',
    definitely: 'Yes', maybe: 'Maybe', probablyNot: 'No',
    feedbackQuestion: 'What would make this better? (optional)', feedbackPlaceholder: 'One short suggestion…',
    saveResponse: 'Save response', savedHere: 'Your response stays on this device.',
    unavailable: 'Lesson not found.', applyConcept: 'Try it now',
    submitDecision: 'Submit choice', continue: 'Continue', bestOrder: 'Better order',
    mostToLeast: 'Most useful to least useful',
    moveUp: 'Move up', moveDown: 'Move down', submitRanking: 'Check order',
    chooseCategory: 'Choose one group for each clue', bestFit: 'Better fit',
    checkMap: 'Check answers', placedWell: 'placed well',
    chooseExactly: 'Choose', useful: 'Useful', lessUseful: 'Less useful',
    submitEvidence: 'Submit clues', multiCorrect: 'These two clues help most with the decision.',
    multiIncorrect: 'First check value and how many people have the problem.',
    strongDecision: 'Good choice', partialDecision: 'Partly right', notQuite: 'Not quite',
    backToLessons: 'Back to lessons',
  },
};

export const futureTopics = {
  fa: [
    ['شناخت فرصت‌ها', 'حرف مردم یا رفتارشان؟'],
    ['شناخت فرصت‌ها', 'کدام سرنخ قوی‌تر است؟'],
    ['طراحی تجربه', 'نقشهٔ یک خدمت'],
    ['عددهای محصول', 'عددهایی که به هدف اصلی کمک می‌کنند'],
    ['آزمایش', 'کوچک‌ترین تغییری که می‌توان دید'],
    ['راهِ محصول', 'انتخاب‌های مهم و بده‌بستان‌ها'],
    ['اولویت‌بندی', 'چه وقت به رتبهٔ RICE تکیه نکنیم؟'],
    ['ساخت و ارائه', 'ارائهٔ مرحله‌به‌مرحله'],
    ['دانش فنی', 'نسخه‌های API و سازگاری آنها'],
  ],
  en: [
    ['Discovery', 'What people say vs what they do'],
    ['Discovery', 'Which clue is stronger?'],
    ['Experience design', 'Map a service'],
    ['Product numbers', 'Numbers that move the main goal'],
    ['Experiments', 'The smallest change you can detect'],
    ['Product strategy', 'Big choices and trade-offs'],
    ['Prioritization', 'When a RICE score should not decide'],
    ['Delivery', 'Release a change step by step'],
    ['Technical basics', 'API versions and compatibility'],
  ],
};
